### ISSUE TITLE
Database refactor

### ISSUE THREAD

**Issue by jooaodanieel** [Digi-Dojo/MService-TasksAndCalendars#4]
SpringBoot already ships an easy-to-use database management, based on configuration files and annotations. Query builders, .sql files, and migrations are not necessary for the most standard use of the framework.

- Tables can be defined by further annotating Entities, e.g.:

```java
@Entity
@Table(name = "DigiUsers")
public class User {
    // ...
}
```

- Queries come out-of-the-box with `JpaRepository` and can be extended following naming conventions, e.g.:

```java
public interface UserRepository extends JpaRepository<User, Long> {
    
    // returns a single user, or none
    Optional<User> findByEmail(String email);

    // returns a list (empty or filled) of users
    List<User> findAllByEmail(String email);
}
```

**Comment by AntonioCoppe** [comment]
Completed
