### ISSUE TITLE
Refactor directories

### ISSUE THREAD

**Issue by jooaodanieel** [Digi-Dojo/MService-TasksAndCalendars#5]
The division of services and of layers is mixed. It's understood you defined records for representing important concepts that are responsibility of other services (namely Users and Places). For that, we're pushing the structure a little, by creating three subdomains: `calendar` and `task` that are properly, and `common` that is dedicated to those external representations.

> **Note**: `domain` is where the business logic lies, whereas `application` is where the connection to the external world lies.

Refactor so that it follows:

```
- it.unibz.taskcalendarservice
    - common
        - domain
            - Place.java
            - User.java
    - calendar
        - domain
            - CalendarEvent.java
            - CalendarEventRepository.java
            - CalendarEventService.java
        - application
            - CalendarEventController.java
    - task
        - domain
            - Task.java
            - TaskRepository.java
            - TaskService.java
        - application
            - TaskController.java
```

**Comment by AntonioCoppe** [comment]
Refactoring finished

**Comment by AntonioCoppe** [comment]
Refactor done in separate branch
